# Generated by Django 4.2.11 on 2025-01-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_etudiant_datofbirth_etudiant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(help_text='Veuillez entrer un adresse email valide', max_length=254, null=True, unique=True, verbose_name='Adresse e-mail'),
        ),
    ]
