# Generated by Django 4.2.11 on 2025-01-16 09:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_alter_etudiant_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('someData', models.JSONField(default=dict)),
            ],
        ),
    ]
