# Generated by Django 4.2.11 on 2025-01-11 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_etudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='datOfBirth',
            field=models.DateField(default=datetime.date.today, help_text='Fromat : AAAA-MM-JJ', null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(help_text='Veuillew entrer un adresse email valide', max_length=254, null=True, unique=True, verbose_name='Adresse e-mail'),
        ),
    ]
